"""
VTT Parser Module

This module handles the parsing of VTT format transcripts, specifically those generated by MacWhisper.
It converts VTT formatted transcripts into a standardized internal format with timestamps and content.
"""

from pathlib import Path
from typing import List, Dict, Any, Optional
import logging

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class VTTParser:
    """Parser for VTT format transcripts from MacWhisper."""
    
    def __init__(self, vtt_path: Path) -> None:
        """
        Initialize the VTT parser.
        
        Args:
            vtt_path (Path): Path to the VTT file to parse
        """
        self.vtt_path = Path(vtt_path)
        if not self.vtt_path.exists():
            raise FileNotFoundError(f"VTT file not found: {vtt_path}")
        
    def parse(self) -> List[Dict[str, Any]]:
        """
        Parse VTT file into segments with timestamps and content.
        
        Returns:
            List[Dict]: List of segments, each containing:
                - timestamp (float): Start time in seconds
                - content (str): Text content of the segment
                
        Raises:
            ValueError: If the VTT file is malformed
            IOError: If there are issues reading the file
        """
        try:
            with open(self.vtt_path, 'r', encoding='utf-8') as file:
                lines = file.readlines()
        except IOError as e:
            logger.error(f"Error reading VTT file: {e}")
            raise
            
        segments = []
        current_time = None
        current_content = []
        
        try:
            for line_num, line in enumerate(lines, 1):
                line = line.strip()
                if not line or line == 'WEBVTT':
                    continue
                    
                # Check for timestamp line (e.g., "00:00:00.000 --> 00:00:05.000")
                if '-->' in line:
                    # Save previous segment if exists
                    if current_time is not None and current_content:
                        segments.append({
                            'timestamp': current_time,
                            'content': ' '.join(current_content)
                        })
                        current_content = []
                    
                    # Parse new timestamp
                    try:
                        start_time = line.split(' --> ')[0]
                        current_time = self._parse_timestamp(start_time)
                    except (IndexError, ValueError) as e:
                        logger.error(f"Invalid timestamp format at line {line_num}: {line}")
                        raise ValueError(f"Invalid timestamp at line {line_num}: {e}")
                else:
                    current_content.append(line)
            
            # Add the last segment
            if current_time is not None and current_content:
                segments.append({
                    'timestamp': current_time,
                    'content': ' '.join(current_content)
                })
                
            if not segments:
                logger.warning("No segments found in VTT file")
                
            logger.info(f"Successfully parsed {len(segments)} segments from VTT file")
            return segments
            
        except Exception as e:
            logger.error(f"Error parsing VTT file: {e}")
            raise
    
    def _parse_timestamp(self, timestamp: str) -> float:
        """
        Convert VTT timestamp to seconds.
        
        Args:
            timestamp (str): Timestamp in HH:MM:SS.mmm or MM:SS.mmm format
            
        Returns:
            float: Time in seconds
            
        Raises:
            ValueError: If timestamp format is invalid
        """
        try:
            # Handle both HH:MM:SS.mmm and MM:SS.mmm formats
            parts = timestamp.replace(',', '.').split(':')
            if len(parts) == 3:  # HH:MM:SS.mmm
                hours, minutes, seconds = parts
                return float(hours) * 3600 + float(minutes) * 60 + float(seconds)
            elif len(parts) == 2:  # MM:SS.mmm
                minutes, seconds = parts
                return float(minutes) * 60 + float(seconds)
            else:
                raise ValueError(f"Invalid timestamp format: {timestamp}")
        except (ValueError, IndexError) as e:
            raise ValueError(f"Error parsing timestamp {timestamp}: {str(e)}") 