name: podcast_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - textblob
  - librosa
  - plotly
  - ffmpeg
  - pip
  - scikit-learn
  - pytorch
  - torchaudio
  - pip:
    - openai-whisper
    - pydub
    - webvtt-py
    - pyannote.audio
    - torch-audiomentations
    - speechbrain
    - myprosody
    - ipython
    - praat-parselmouth
    - elevenlabs 